# Generated by Django 2.0.3 on 2018-03-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(max_length=12)),
                ('naam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('omschrijving', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grondslag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(max_length=12)),
                ('omschrijving', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medewerker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(max_length=12)),
                ('naam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedewerkerRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('gedefinieerd_door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Applicatie')),
                ('is_geautoriseerd_voor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataObject')),
                ('wordt_vervuld_door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Medewerker')),
            ],
        ),
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(max_length=12)),
                ('naam', models.CharField(max_length=255)),
                ('adres', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(max_length=12)),
                ('naam', models.CharField(max_length=300)),
                ('verwerkings_verantwoordelijke', models.CharField(max_length=100)),
                ('organisatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voert_uit', to='datamodel.Organisatie')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesStap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(max_length=12)),
                ('naam', models.CharField(max_length=255)),
                ('bewaartermijn', models.PositiveSmallIntegerField()),
                ('gebaseerd_op', models.ManyToManyField(to='datamodel.Grondslag')),
                ('proces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestaat_uit', to='datamodel.Proces')),
                ('realiseert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Doel')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('heeft_betrekking_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ProcesStap')),
                ('wordt_vervuld_door_applicatie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Applicatie')),
                ('wordt_vervuld_door_organisatie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Organisatie')),
            ],
        ),
        migrations.AddField(
            model_name='dataobject',
            name='organisatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_bronhouder_van', to='datamodel.Organisatie'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='data_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omvat', to='datamodel.DataObject'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='process_stap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mag_bewerken', to='datamodel.ProcesStap'),
        ),
    ]
