# Generated by Django 2.0.3 on 2018-03-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicatie',
            options={'verbose_name': 'applicatie', 'verbose_name_plural': 'applicaties'},
        ),
        migrations.AlterModelOptions(
            name='dataelement',
            options={'verbose_name': 'data element', 'verbose_name_plural': 'data elementen'},
        ),
        migrations.AlterModelOptions(
            name='dataobject',
            options={'verbose_name': 'data object', 'verbose_name_plural': 'data objecten'},
        ),
        migrations.AlterModelOptions(
            name='doel',
            options={'verbose_name': 'doel', 'verbose_name_plural': 'doelen'},
        ),
        migrations.AlterModelOptions(
            name='grondslag',
            options={'verbose_name': 'grondslag', 'verbose_name_plural': 'grondslagen'},
        ),
        migrations.AlterModelOptions(
            name='medewerker',
            options={'verbose_name': 'medewerker', 'verbose_name_plural': 'medewerkers'},
        ),
        migrations.AlterModelOptions(
            name='medewerkerrol',
            options={'verbose_name': 'medewerker rol', 'verbose_name_plural': 'medewerker rollen'},
        ),
        migrations.AlterModelOptions(
            name='organisatie',
            options={'verbose_name': 'organisatie', 'verbose_name_plural': 'organisaties'},
        ),
        migrations.AlterModelOptions(
            name='proces',
            options={'verbose_name': 'proces', 'verbose_name_plural': 'processen'},
        ),
        migrations.AlterModelOptions(
            name='processtap',
            options={'verbose_name': 'proces stap', 'verbose_name_plural': 'proces stappen'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'rollen'},
        ),
        migrations.RenameField(
            model_name='dataobject',
            old_name='organisatie',
            new_name='bronhouder',
        ),
        migrations.RenameField(
            model_name='medewerkerrol',
            old_name='gedefinieerd_door',
            new_name='gedefinieerd_voor',
        ),
        migrations.RemoveField(
            model_name='applicatie',
            name='identificatie',
        ),
        migrations.RemoveField(
            model_name='grondslag',
            name='identificatie',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='identificatie',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='identificatie',
        ),
        migrations.RemoveField(
            model_name='proces',
            name='identificatie',
        ),
        migrations.RemoveField(
            model_name='processtap',
            name='identificatie',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='process_stap',
        ),
        migrations.AddField(
            model_name='dataelement',
            name='process_stap',
            field=models.ManyToManyField(related_name='mag_bewerken', to='datamodel.ProcesStap'),
        ),
        migrations.AlterField(
            model_name='medewerkerrol',
            name='is_geautoriseerd_voor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataObject', verbose_name='is geautoriseerd voor (data object)'),
        ),
        migrations.AlterField(
            model_name='medewerkerrol',
            name='wordt_vervuld_door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Medewerker', verbose_name='wordt vervuld door (medewerker)'),
        ),
        migrations.AlterField(
            model_name='processtap',
            name='gebaseerd_op',
            field=models.ManyToManyField(to='datamodel.Grondslag', verbose_name='gebaseerd op (grondslag)'),
        ),
        migrations.AlterField(
            model_name='processtap',
            name='realiseert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Doel', verbose_name='realiseert (doel)'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='heeft_betrekking_op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ProcesStap', verbose_name='heeft betreking op (proces stap)'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='naam',
            field=models.CharField(choices=[('Gegevensontvanger', 'Gegevensontvanger'), ('Gegevensaanbieder', 'Gegevensaanbieder'), ('Gegevensverwerker', 'Gegevensverwerker'), ('Eventontvanger', 'Eventontvanger'), ('Eventaanbieder', 'Eventaanbieder'), ('Eventverwerker', 'Eventverwerker')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rol',
            name='wordt_vervuld_door_applicatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Applicatie', verbose_name='wordt vervuld door (applicatie)'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='wordt_vervuld_door_organisatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Organisatie', verbose_name='wordt vervuld door (organisatie)'),
        ),
        migrations.AlterField(
            model_name='dataobject',
            name='bronhouder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_bronhouder_van', to='datamodel.Organisatie', verbose_name='bronhouder (organisatie)'),
        ),
        migrations.AlterField(
            model_name='medewerkerrol',
            name='gedefinieerd_voor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Applicatie', verbose_name='gedefinieerd voor (applicatie)'),
        ),
    ]
