# Generated by Django 2.0.3 on 2018-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20180307_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'Regels',
                'verbose_name': 'Regel',
                'proxy': True,
            },
            bases=('datamodel.processtap',),
        ),
        migrations.AddField(
            model_name='dataobject',
            name='privacy_classificatie',
            field=models.CharField(choices=[('Open data', 'Open data'), ('Valt onder AVG', 'Valt onder AVG'), ('Overig', 'Overig')], default='Overig', max_length=100),
        ),
    ]
