# Generated by Django 2.0.3 on 2018-03-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20180307_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='process_stap',
            field=models.ManyToManyField(blank=True, related_name='mag_bewerken', to='datamodel.ProcesStap'),
        ),
    ]
