# Generated by Django 2.0.3 on 2018-03-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achternaam', models.CharField(max_length=200)),
                ('voornaam', models.CharField(blank=True, max_length=200)),
                ('adres', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'persoon',
                'verbose_name_plural': 'personen',
            },
        ),
        migrations.CreateModel(
            name='VergunningsAanvraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaaktype', models.CharField(choices=[('Bouwvergunningsaanvraag', 'Bouwvergunningsaanvraag')], max_length=50)),
                ('zaakstatus', models.CharField(choices=[('In behandeling', 'In behandeling'), ('Afgewezen', 'Afgewezen'), ('Toegewezen', 'Toegewezen')], max_length=50)),
                ('lokatie_postcode', models.CharField(max_length=7)),
                ('lokatie_huisnummer', models.CharField(max_length=10)),
                ('lokatie_huisnummer_toevoeging', models.CharField(blank=True, max_length=20)),
                ('aanvrager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Persoon')),
            ],
        ),
    ]
