# Generated by Django 2.0.3 on 2018-03-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vergunningsaanvraag',
            options={'verbose_name': 'vergunningsaanvraag', 'verbose_name_plural': 'vergunningsaanvragen'},
        ),
        migrations.AddField(
            model_name='vergunningsaanvraag',
            name='onderwerp',
            field=models.CharField(default='dakkapel', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vergunningsaanvraag',
            name='toelichting',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vergunningsaanvraag',
            name='zaakstatus',
            field=models.CharField(choices=[('Nieuw', 'Nieuw'), ('In behandeling', 'In behandeling'), ('Afgewezen', 'Afgewezen'), ('Toegewezen', 'Toegewezen')], default='Nieuw', max_length=50),
        ),
    ]
