# Generated by Django 2.0.3 on 2018-03-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20180308_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vergunningsaanvraag',
            options={'ordering': ['-created'], 'verbose_name': 'vergunningsaanvraag', 'verbose_name_plural': 'vergunningsaanvragen'},
        ),
    ]
